import { useState } from "react";
import Head from "next/head";
import cn from "classnames";
import { Cormorant_Garamond } from "@next/font/google";
import styles from "../styles/Home.module.css";

const fontFamily = Cormorant_Garamond({
  weight: ["400", "600"],
  subsets: ["latin"],
});

const Lettered = ({
  duration = 1,
  visible = true,
  text,
  delayStep = 0.1,
}: {
  duration?: number;
  visible?: boolean;
  text?: string;
  delayStep?: number;
}) => {
  if (!text) return null;

  return (
    <div
      className={cn(
        styles.lettered,
        visible ? styles.letteredVisible : styles.letteredHidden
      )}
    >
      {Array.from(text).map((letter, index) => {
        const delayStyle: React.CSSProperties = {
          animationDelay: `${delayStep * index}s`,
        };

        const durationStyle: React.CSSProperties = {
          animationDuration: `${duration}s`,
        };

        const animationStyle = {
          ...durationStyle,
          ...delayStyle,
        };

        return (
          <div key={letter} className={styles.letterContainer}>
            <div style={animationStyle} className={styles.letterCharacter}>
              {letter}
            </div>
          </div>
        );
      })}
    </div>
  );
};

export default function Home() {
  const [visible, setVisibility] = useState<boolean>(true);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={cn(fontFamily.className, styles.title)}>
          <Lettered
            text="IzmaelMag"
            duration={1}
            delayStep={0.05}
            visible={visible}
          />
        </h1>

        <button onClick={() => setVisibility(!visible)}>Toggle</button>
      </main>
    </>
  );
}
